# Generated by Django 4.1.3 on 2022-11-23 14:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('type', models.CharField(max_length=64, unique=True)),
                ('title', models.CharField(max_length=256)),
                ('url', models.URLField()),
                ('status', models.SmallIntegerField(default=1)),
                ('logo', models.ImageField(upload_to='static/img/')),
                ('address', models.CharField(max_length=256)),
                ('map_location', models.CharField(max_length=2048)),
                ('map_location_iframe', models.CharField(max_length=2048)),
                ('updated_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'contanct',
            },
        ),
        migrations.CreateModel(
            name='ProductCard',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('heighliter', models.CharField(max_length=128)),
                ('title', models.CharField(max_length=256)),
                ('status', models.SmallIntegerField(default=1)),
                ('img', models.ImageField(upload_to='static/img/')),
                ('updated_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'product_card',
            },
        ),
        migrations.CreateModel(
            name='SiteData',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('status', models.SmallIntegerField(default=1)),
                ('logo', models.ImageField(upload_to='static/img/')),
                ('banner', models.ImageField(upload_to='static/img/')),
                ('about_us', models.ImageField(upload_to='static/img/')),
                ('updated_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'site_data',
            },
        ),
        migrations.CreateModel(
            name='SocialMedia',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('platform', models.CharField(max_length=64, unique=True)),
                ('title', models.CharField(max_length=256)),
                ('url', models.URLField()),
                ('status', models.SmallIntegerField(default=1)),
                ('logo', models.ImageField(upload_to='static/img/')),
                ('updated_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'socialmedia',
            },
        ),
    ]
