# Generated by Django 4.1.3 on 2022-11-23 15:11

import core_app.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='filename',
            field=models.CharField(default='j', max_length=1080),
        ),
        migrations.AddField(
            model_name='productcard',
            name='filename',
            field=models.CharField(default='j', max_length=1080),
        ),
        migrations.AddField(
            model_name='sitedata',
            name='about_usfilename',
            field=models.CharField(default='j', max_length=1080),
        ),
        migrations.AddField(
            model_name='sitedata',
            name='bannerfilename',
            field=models.CharField(default='j', max_length=1080),
        ),
        migrations.AddField(
            model_name='sitedata',
            name='logofilename',
            field=models.CharField(default='j', max_length=1080),
        ),
        migrations.AddField(
            model_name='socialmedia',
            name='filename',
            field=models.CharField(default='j', max_length=1080),
        ),
        migrations.AlterField(
            model_name='contact',
            name='logo',
            field=models.ImageField(upload_to=core_app.models.filepath),
        ),
        migrations.AlterField(
            model_name='productcard',
            name='img',
            field=models.ImageField(upload_to=core_app.models.filepath),
        ),
        migrations.AlterField(
            model_name='sitedata',
            name='about_us',
            field=models.ImageField(upload_to=core_app.models.filepath),
        ),
        migrations.AlterField(
            model_name='sitedata',
            name='banner',
            field=models.ImageField(upload_to=core_app.models.filepath),
        ),
        migrations.AlterField(
            model_name='sitedata',
            name='logo',
            field=models.ImageField(upload_to=core_app.models.filepath),
        ),
        migrations.AlterField(
            model_name='socialmedia',
            name='logo',
            field=models.ImageField(upload_to=core_app.models.filepath),
        ),
    ]
