# Generated by Django 4.1.3 on 2022-11-23 15:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core_app', '0002_contact_filename_productcard_filename_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='filename',
            field=models.CharField(max_length=1080),
        ),
        migrations.AlterField(
            model_name='productcard',
            name='filename',
            field=models.CharField(max_length=1080),
        ),
        migrations.AlterField(
            model_name='sitedata',
            name='about_usfilename',
            field=models.CharField(max_length=1080),
        ),
        migrations.AlterField(
            model_name='sitedata',
            name='bannerfilename',
            field=models.CharField(max_length=1080),
        ),
        migrations.AlterField(
            model_name='sitedata',
            name='logofilename',
            field=models.CharField(max_length=1080),
        ),
        migrations.AlterField(
            model_name='socialmedia',
            name='filename',
            field=models.CharField(max_length=1080),
        ),
    ]
